<?php
/**
 * @category    Fishpig
 * @package     Fishpig_Wordpress
 * @license     http://fishpig.co.uk/license.txt
 * @author      Ben Tideswell <help@fishpig.co.uk>
 */
?>
<?php $post = $this->getPost() ?>
<?php if ($post): ?>
<p class="post-meta details">
	<?php
		$catNames = explode(',', $this->getCategoryString($post));
		foreach ($catNames as $catName) {
			$catName = trim($catName);
			$catName = strtolower(str_replace(" ", "-", $catName));
			$catName = str_replace("!", "", $catName);
			$catName = str_replace("'", "", $catName);
			$catName = str_replace("&amp;", "-", $catName);
			echo '<img src="/wp/wp-content/uploads/2014/12/'. strip_tags($catName) .'.jpg" />' ;
		}
		
	?>
	<br />
	<?php echo stripslashes($this->__('%s', $this->getCategoryString($post))) ?>
<?php /* if ($this->canDisplayPreviousNextLinks()): ?>
<span class="post-skips">
	<?php if (($previous = $post->getPreviousPost()) !== false): ?>
		<a href="<?php echo $previous->getPermalink() ?>" class="post-skip post-skip-previous" title="<?php echo $this->escapeHtml($previous->getPostTitle()) ?>">&larr; <?php echo $this->__('Previous Post') ?></a>
	<?php endif; ?>
	<?php if (($next = $post->getNextPost()) !== false): ?>
		<a href="<?php echo $next->getPermalink() ?>" class="post-skip post-skip-next right" title="<?php echo $this->escapeHtml($next->getPostTitle()) ?>"><?php echo $this->__('Next Post') ?> &rarr;</a>
	<?php endif; ?>
</span>
<?php endif; */ ?>
</p>
<?php endif; ?>