<div class="social">
	<div class="instagram">
	    <div class="content">
	    	<header>
				<icon class="fa fa-instagram fa-2x"></icon><br/>
				<a href="" class="nomobile">#whitmoreandwhite</a>
	    	</header>
			<?php $images = $this->getInstagramImages();  ?>
			<ul class="nomobile">
			<?php foreach($images as $image):?>
			
				<li class="">
					<img src="<?php echo $image['low_res']?>" />
				</li>
			
			<?php endforeach; ?>
			</ul>
		</div>
	</div>
	<div class="twitter">
	     <div class="content">
	     	<header>
				<icon class="fa fa-twitter fa-2x"></icon><br/>
				<a href="" class="nomobile">@whitmoreandwhite</a>
	     	</header>
			<ul class="nomobile">
				<li>
					Did you know we stock a range of beautiful Olive Wood cheese boards, olive dishes and kitchenalia? #Heswall <a href="">#Wirral pic.twitter.com/ZVJtqW0rwS</a>
				</li>
			</ul>
	     </div>
	</div>
	<div class="facebook">
	     <div class="content">
	     	<header>
				<icon class="fa fa-facebook fa-2x"></icon><br/>
				<a href="" class="nomobile">whitmoreandwhite</a>
	     	</header>
	     </div>
	</div>
</div>